import type { Database } from "./models";

export const DB_VERSION = 1;

function isoDate(offsetDays: number) {
  const d = new Date();
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString().slice(0, 10);
}

function isoAt(offsetDays: number, hour: number, minute = 0) {
  const d = new Date();
  d.setDate(d.getDate() + offsetDays);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
}

export function createSeedDatabase(): Database {
  return {
    version: DB_VERSION,
    organization: {
      id: "org-1",
      name: "Vetri Infra Works",
      legalName: "Vetri Infra Works Pvt Ltd",
      industry: "Construction & precast",
      timezone: "Asia/Kolkata",
      currency: "INR",
      standardShiftHours: 9,
      overtimeAfterHours: 9,
      geofenceRadiusM: 150,
      requireCheckInPhoto: true,
      requireGpsVerification: true,
      autoApproveAttendance: false,
      contactEmail: "ops@vetriinfra.in",
      contactPhone: "+91 90031 55480",
    },
    users: [
      {
        id: "u-admin",
        name: "Anand Raj",
        email: "anand@shiftrio.app",
        phone: "+91 98400 10101",
        role: "admin",
        avatarInitials: "AR",
        language: "en",
      },
      {
        id: "u-staff",
        name: "Murugan S",
        email: "murugan@shiftrio.app",
        phone: "+91 98400 11223",
        role: "staff",
        workerId: "w-1",
        avatarInitials: "MS",
        language: "en",
      },
    ],
    workers: [
      {
        id: "w-1",
        name: "Murugan S",
        nameTa: "முருகன் ச",
        employeeCode: "VIW-1042",
        designation: "Crane Operator",
        phone: "+91 98400 11223",
        siteId: "site-1",
        skills: ["Crane", "Rigging"],
        status: "active",
        joinedAt: "2022-04-11",
        dailyWage: 1250,
        rating: 4.8,
      },
      {
        id: "w-2",
        name: "Priya Lakshmi",
        nameTa: "பிரியா லக்ஷ்மி",
        employeeCode: "VIW-1088",
        designation: "Site Safety Officer",
        phone: "+91 90031 55480",
        siteId: "site-2",
        skills: ["Safety Audit", "First Aid"],
        status: "active",
        joinedAt: "2021-09-02",
        dailyWage: 1600,
        rating: 4.9,
      },
      {
        id: "w-3",
        name: "Karthik R",
        nameTa: "கார்த்திக் ர",
        employeeCode: "VIW-1130",
        designation: "Welder",
        phone: "+91 99621 78310",
        siteId: "site-1",
        skills: ["MIG", "TIG"],
        status: "active",
        joinedAt: "2023-01-18",
        dailyWage: 1100,
        rating: 4.5,
      },
      {
        id: "w-4",
        name: "Abdul Rahman",
        nameTa: "அப்துல் ரஹ்மான்",
        employeeCode: "VIW-1177",
        designation: "Excavator Operator",
        phone: "+91 89390 22014",
        siteId: "site-3",
        skills: ["Excavator", "Loader"],
        status: "active",
        joinedAt: "2020-06-25",
        dailyWage: 1300,
        rating: 4.6,
      },
      {
        id: "w-5",
        name: "Selvi D",
        nameTa: "செல்வி த",
        employeeCode: "VIW-1201",
        designation: "Bar Bender",
        phone: "+91 94441 90876",
        siteId: "site-2",
        skills: ["Rebar"],
        status: "active",
        joinedAt: "2023-07-04",
        dailyWage: 950,
        rating: 4.4,
      },
      {
        id: "w-6",
        name: "Ravi Chandran",
        nameTa: "ரவி சந்திரன்",
        employeeCode: "VIW-1009",
        designation: "Foreman",
        phone: "+91 97890 44512",
        siteId: "site-1",
        skills: ["Supervision", "Scheduling"],
        status: "active",
        joinedAt: "2019-02-12",
        dailyWage: 1800,
        rating: 4.7,
      },
      {
        id: "w-7",
        name: "Joseph Antony",
        nameTa: "ஜோசப் அந்தோணி",
        employeeCode: "VIW-1244",
        designation: "Electrician",
        phone: "+91 93450 66127",
        siteId: "site-2",
        skills: ["LV Wiring", "Panels"],
        status: "on_leave",
        joinedAt: "2022-11-30",
        dailyWage: 1150,
        rating: 4.1,
      },
      {
        id: "w-8",
        name: "Devi Shankar",
        nameTa: "தேவி சங்கர்",
        employeeCode: "VIW-1260",
        designation: "Concrete Technician",
        phone: "+91 96770 30945",
        siteId: "site-3",
        skills: ["Mix Design", "Curing"],
        status: "active",
        joinedAt: "2021-03-15",
        dailyWage: 1400,
        rating: 4.6,
      },
      {
        id: "w-9",
        name: "Ilango P",
        nameTa: "இளங்கோ ப",
        employeeCode: "VIW-1288",
        designation: "Helper",
        phone: "+91 90876 12233",
        siteId: "site-4",
        skills: ["Material handling"],
        status: "inactive",
        joinedAt: "2024-01-08",
        dailyWage: 780,
        rating: 3.9,
      },
    ],
    sites: [
      {
        id: "site-1",
        name: "Kovai Steel Yard",
        code: "KSY-01",
        city: "Coimbatore",
        address: "SIDCO Industrial Estate, Kurichi, Coimbatore 641021",
        inchargeId: "inc-1",
        headcountTarget: 22,
        status: "active",
        geofenceRadiusM: 150,
        lat: 10.9601,
        lng: 76.9629,
      },
      {
        id: "site-2",
        name: "Marina Tower Block B",
        code: "MTB-04",
        city: "Chennai",
        address: "Rajiv Gandhi Salai, Perungudi, Chennai 600096",
        inchargeId: "inc-2",
        headcountTarget: 26,
        status: "active",
        geofenceRadiusM: 120,
        lat: 12.9698,
        lng: 80.2456,
      },
      {
        id: "site-3",
        name: "Hosur Precast Plant",
        code: "HPP-02",
        city: "Hosur",
        address: "SIPCOT Phase II, Hosur 635109",
        inchargeId: "inc-3",
        headcountTarget: 16,
        status: "active",
        geofenceRadiusM: 200,
        lat: 12.7409,
        lng: 77.8253,
      },
      {
        id: "site-4",
        name: "Trichy Bypass Roadworks",
        code: "TBR-07",
        city: "Tiruchirappalli",
        address: "NH-38 Bypass, Thuvakudi, Tiruchirappalli 620015",
        inchargeId: "inc-4",
        headcountTarget: 12,
        status: "paused",
        geofenceRadiusM: 300,
        lat: 10.7905,
        lng: 78.7047,
      },
    ],
    machines: [
      {
        id: "m-1",
        name: "Tower Crane TC-02",
        code: "TC-02",
        category: "Crane",
        siteId: "site-1",
        status: "in_use",
        lastServicedAt: isoDate(-24),
        hoursRun: 4210,
      },
      {
        id: "m-2",
        name: "Excavator EX-210",
        code: "EX-210",
        category: "Earthmoving",
        siteId: "site-3",
        status: "in_use",
        lastServicedAt: isoDate(-11),
        hoursRun: 2860,
      },
      {
        id: "m-3",
        name: "Batching Plant BP-1",
        code: "BP-1",
        category: "Concrete",
        siteId: "site-3",
        status: "available",
        lastServicedAt: isoDate(-40),
        hoursRun: 7320,
      },
      {
        id: "m-4",
        name: "Concrete Pump CP-05",
        code: "CP-05",
        category: "Concrete",
        siteId: "site-2",
        status: "available",
        lastServicedAt: isoDate(-6),
        hoursRun: 1180,
      },
      {
        id: "m-5",
        name: "Backhoe Loader BL-3",
        code: "BL-3",
        category: "Earthmoving",
        siteId: "site-4",
        status: "maintenance",
        lastServicedAt: isoDate(-2),
        hoursRun: 5140,
      },
      {
        id: "m-6",
        name: "Welding Rig WR-11",
        code: "WR-11",
        category: "Fabrication",
        siteId: "site-1",
        status: "available",
        lastServicedAt: isoDate(-15),
        hoursRun: 940,
      },
    ],
    operators: [
      {
        id: "op-1",
        name: "Murugan S",
        phone: "+91 98400 11223",
        licenseNo: "TN-CR-88421",
        certifiedFor: ["Crane", "Rigging"],
        siteId: "site-1",
        status: "assigned",
      },
      {
        id: "op-2",
        name: "Abdul Rahman",
        phone: "+91 89390 22014",
        licenseNo: "TN-EX-51190",
        certifiedFor: ["Earthmoving"],
        siteId: "site-3",
        status: "assigned",
      },
      {
        id: "op-3",
        name: "Suresh Babu",
        phone: "+91 90032 77118",
        licenseNo: "TN-CP-33902",
        certifiedFor: ["Concrete"],
        siteId: "site-2",
        status: "available",
      },
      {
        id: "op-4",
        name: "Manikandan V",
        phone: "+91 97865 44012",
        licenseNo: "TN-BL-11245",
        certifiedFor: ["Earthmoving", "Crane"],
        siteId: "site-4",
        status: "off_duty",
      },
    ],
    incharges: [
      {
        id: "inc-1",
        name: "Anand Raj",
        phone: "+91 98400 10101",
        email: "anand@vetriinfra.in",
        siteId: "site-1",
        shiftPreference: "day",
      },
      {
        id: "inc-2",
        name: "Fatima Noor",
        phone: "+91 90031 20304",
        email: "fatima@vetriinfra.in",
        siteId: "site-2",
        shiftPreference: "any",
      },
      {
        id: "inc-3",
        name: "Vignesh K",
        phone: "+91 99401 55667",
        email: "vignesh@vetriinfra.in",
        siteId: "site-3",
        shiftPreference: "night",
      },
      {
        id: "inc-4",
        name: "Sundar M",
        phone: "+91 94425 90011",
        email: "sundar@vetriinfra.in",
        siteId: "site-4",
        shiftPreference: "day",
      },
    ],
    shifts: [
      {
        id: "sh-1",
        workerId: "w-2",
        siteId: "site-2",
        machineId: null,
        operatorId: null,
        inchargeId: "inc-2",
        shiftType: "day",
        startedAt: isoAt(0, 7, 2),
        endedAt: null,
        breakMinutes: 0,
        status: "active",
        checkInPhoto: {
          id: "ph-1",
          dataUrl: null,
          fileName: "checkin-priya.jpg",
          kind: "check_in",
          takenAt: isoAt(0, 7, 2),
          source: "camera",
        },
        checkOutPhoto: null,
        checkInLocation: {
          verified: true,
          distanceM: 42,
          accuracyM: 8,
          lat: 12.9698,
          lng: 80.2456,
          method: "simulated",
          checkedAt: isoAt(0, 7, 2),
        },
        notes: "Safety walkaround before crew entry.",
      },
      {
        id: "sh-2",
        workerId: "w-4",
        siteId: "site-3",
        machineId: "m-2",
        operatorId: "op-2",
        inchargeId: "inc-3",
        shiftType: "day",
        startedAt: isoAt(0, 6, 45),
        endedAt: null,
        breakMinutes: 30,
        status: "active",
        checkInPhoto: null,
        checkOutPhoto: null,
        checkInLocation: {
          verified: true,
          distanceM: 96,
          accuracyM: 12,
          lat: 12.7409,
          lng: 77.8253,
          method: "simulated",
          checkedAt: isoAt(0, 6, 45),
        },
        notes: "",
      },
      {
        id: "sh-3",
        workerId: "w-8",
        siteId: "site-3",
        machineId: "m-3",
        operatorId: null,
        inchargeId: "inc-3",
        shiftType: "day",
        startedAt: isoAt(0, 7, 30),
        endedAt: null,
        breakMinutes: 0,
        status: "active",
        checkInPhoto: null,
        checkOutPhoto: null,
        checkInLocation: {
          verified: false,
          distanceM: 260,
          accuracyM: 30,
          lat: 12.7409,
          lng: 77.8253,
          method: "simulated",
          checkedAt: isoAt(0, 7, 30),
        },
        notes: "Outside geofence at check-in — flagged for review.",
      },
      {
        id: "sh-4",
        workerId: "w-1",
        siteId: "site-1",
        machineId: "m-1",
        operatorId: "op-1",
        inchargeId: "inc-1",
        shiftType: "day",
        startedAt: isoAt(-1, 6, 5),
        endedAt: isoAt(-1, 16, 35),
        breakMinutes: 45,
        status: "completed",
        checkInPhoto: null,
        checkOutPhoto: null,
        checkInLocation: {
          verified: true,
          distanceM: 30,
          accuracyM: 9,
          lat: 10.9601,
          lng: 76.9629,
          method: "simulated",
          checkedAt: isoAt(-1, 6, 5),
        },
        notes: "Beam lifts for grid 4-7.",
      },
      {
        id: "sh-5",
        workerId: "w-3",
        siteId: "site-1",
        machineId: "m-6",
        operatorId: null,
        inchargeId: "inc-1",
        shiftType: "night",
        startedAt: isoAt(-2, 19, 0),
        endedAt: isoAt(-1, 4, 15),
        breakMinutes: 40,
        status: "completed",
        checkInPhoto: null,
        checkOutPhoto: null,
        checkInLocation: {
          verified: true,
          distanceM: 55,
          accuracyM: 10,
          lat: 10.9601,
          lng: 76.9629,
          method: "simulated",
          checkedAt: isoAt(-2, 19, 0),
        },
        notes: "Night fabrication run.",
      },
      {
        id: "sh-6",
        workerId: "w-5",
        siteId: "site-2",
        machineId: null,
        operatorId: null,
        inchargeId: "inc-2",
        shiftType: "day",
        startedAt: isoAt(-2, 7, 45),
        endedAt: isoAt(-2, 17, 0),
        breakMinutes: 45,
        status: "completed",
        checkInPhoto: null,
        checkOutPhoto: null,
        checkInLocation: null,
        notes: "",
      },
      {
        id: "sh-7",
        workerId: "w-1",
        siteId: "site-1",
        machineId: "m-1",
        operatorId: "op-1",
        inchargeId: "inc-1",
        shiftType: "day",
        startedAt: isoAt(-3, 6, 0),
        endedAt: isoAt(-3, 15, 10),
        breakMinutes: 45,
        status: "completed",
        checkInPhoto: null,
        checkOutPhoto: null,
        checkInLocation: null,
        notes: "",
      },
      {
        id: "sh-8",
        workerId: "w-1",
        siteId: "site-1",
        machineId: "m-6",
        operatorId: null,
        inchargeId: "inc-1",
        shiftType: "night",
        startedAt: isoAt(-5, 19, 30),
        endedAt: isoAt(-4, 5, 0),
        breakMinutes: 60,
        status: "completed",
        checkInPhoto: null,
        checkOutPhoto: null,
        checkInLocation: null,
        notes: "Rebar cage welding.",
      },
    ],
    assignments: [
      {
        id: "as-1",
        workerId: "w-1",
        siteId: "site-1",
        machineId: "m-1",
        inchargeId: "inc-1",
        date: isoDate(0),
        shiftType: "day",
        startTime: "06:00",
        endTime: "15:00",
        status: "confirmed",
        note: "Beam erection grid 8-11",
      },
      {
        id: "as-2",
        workerId: "w-3",
        siteId: "site-1",
        machineId: "m-6",
        inchargeId: "inc-1",
        date: isoDate(0),
        shiftType: "night",
        startTime: "19:00",
        endTime: "04:00",
        status: "scheduled",
        note: "",
      },
      {
        id: "as-3",
        workerId: "w-5",
        siteId: "site-2",
        machineId: null,
        inchargeId: "inc-2",
        date: isoDate(1),
        shiftType: "day",
        startTime: "07:30",
        endTime: "16:30",
        status: "scheduled",
        note: "Slab rebar",
      },
      {
        id: "as-4",
        workerId: "w-8",
        siteId: "site-3",
        machineId: "m-3",
        inchargeId: "inc-3",
        date: isoDate(1),
        shiftType: "day",
        startTime: "07:00",
        endTime: "16:00",
        status: "confirmed",
        note: "M40 pours",
      },
      {
        id: "as-5",
        workerId: "w-4",
        siteId: "site-3",
        machineId: "m-2",
        inchargeId: "inc-3",
        date: isoDate(2),
        shiftType: "day",
        startTime: "06:45",
        endTime: "15:45",
        status: "scheduled",
        note: "",
      },
      {
        id: "as-6",
        workerId: "w-2",
        siteId: "site-2",
        machineId: null,
        inchargeId: "inc-2",
        date: isoDate(3),
        shiftType: "day",
        startTime: "07:00",
        endTime: "16:00",
        status: "scheduled",
        note: "Monthly safety audit",
      },
    ],
    attendance: [
      {
        id: "at-1",
        workerId: "w-3",
        siteId: "site-1",
        date: isoDate(0),
        checkIn: "09:22",
        checkOut: null,
        totalHours: 0,
        overtimeHours: 0,
        status: "late",
        shiftType: "day",
      },
      {
        id: "at-2",
        workerId: "w-7",
        siteId: "site-2",
        date: isoDate(0),
        checkIn: null,
        checkOut: null,
        totalHours: 0,
        overtimeHours: 0,
        status: "absent",
        shiftType: "day",
      },
      {
        id: "at-3",
        workerId: "w-6",
        siteId: "site-1",
        date: isoDate(-1),
        checkIn: "06:00",
        checkOut: "16:30",
        totalHours: 10.5,
        overtimeHours: 1.5,
        status: "present",
        shiftType: "day",
      },
      {
        id: "at-4",
        workerId: "w-9",
        siteId: "site-4",
        date: isoDate(-1),
        checkIn: null,
        checkOut: null,
        totalHours: 0,
        overtimeHours: 0,
        status: "absent",
        shiftType: "day",
      },
    ],
    notifications: [
      {
        id: "n-1",
        title: "Geofence exit detected",
        body: "Selvi D left the Marina Tower Block B geofence by 80 m during an active shift.",
        kind: "safety",
        createdAt: new Date(Date.now() - 6 * 60000).toISOString(),
        read: false,
        audience: "admin",
      },
      {
        id: "n-2",
        title: "Check-in without photo",
        body: "Abdul Rahman started a shift at Hosur Precast Plant without a check-in photo.",
        kind: "attendance",
        createdAt: new Date(Date.now() - 48 * 60000).toISOString(),
        read: false,
        audience: "admin",
      },
      {
        id: "n-3",
        title: "Machine maintenance due",
        body: "Backhoe Loader BL-3 is flagged for maintenance and unavailable for assignment.",
        kind: "system",
        createdAt: new Date(Date.now() - 5 * 3600000).toISOString(),
        read: true,
        audience: "admin",
      },
      {
        id: "n-4",
        title: "Tomorrow's shift confirmed",
        body: "Day shift 06:00–15:00 at Kovai Steel Yard with Tower Crane TC-02.",
        kind: "shift",
        createdAt: new Date(Date.now() - 90 * 60000).toISOString(),
        read: false,
        audience: "staff",
      },
      {
        id: "n-5",
        title: "Overtime approved",
        body: "1.5 hours of overtime from yesterday's shift has been approved.",
        kind: "attendance",
        createdAt: new Date(Date.now() - 26 * 3600000).toISOString(),
        read: true,
        audience: "staff",
      },
    ],
  };
}
