import { useCallback, useEffect, useState } from "react";
import { Link } from "@tanstack/react-router";
import { Activity, ArrowUpRight, Clock3, MapPin, RefreshCw, Users } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { getAdminAccess } from "@/lib/admin-access";
import type { Tables } from "@/integrations/supabase/types";
import { Button } from "@/components/ui/button";
import { StatCard } from "./stat-card";
export function AdminDashboard() {
 const [workers, setWorkers] = useState<Tables<"workers">[]>([]); const [sites, setSites] = useState<Tables<"sites">[]>([]); const [shifts, setShifts] = useState<Tables<"shifts">[]>([]); const [events, setEvents] = useState<Tables<"audit_logs">[]>([]);
 const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [now, setNow] = useState(Date.now());
 const load = useCallback(async () => { setLoading(true); setError(""); try { const access = await getAdminAccess(); const results = await Promise.all([supabase.from("workers").select("*").eq("org_id", access.orgId), supabase.from("sites").select("*").eq("org_id", access.orgId), supabase.from("shifts").select("*").eq("org_id", access.orgId).order("started_at", { ascending: false }).limit(500), supabase.from("audit_logs").select("*").eq("org_id", access.orgId).order("created_at", { ascending: false }).limit(6)]); for (const result of results) if (result.error) throw result.error; setWorkers(results[0].data ?? []); setSites(results[1].data ?? []); setShifts(results[2].data ?? []); setEvents(results[3].data ?? []); } catch (err) { setError(err instanceof Error ? err.message : "Unable to load your organization."); } finally { setLoading(false); } }, []);
 useEffect(() => { void load(); const timer = window.setInterval(() => setNow(Date.now()), 1000); return () => window.clearInterval(timer); }, [load]);
 const active = shifts.filter((shift) => shift.status === "active"); const hours = (shift: Tables<"shifts">) => Math.max(0, ((shift.ended_at ? new Date(shift.ended_at).getTime() : now) - new Date(shift.started_at).getTime()) / 3600000 - shift.break_minutes / 60);
 return <div className="mx-auto max-w-6xl space-y-7"><header className="flex items-end justify-between gap-3"><div><p className="text-eyebrow text-primary">Organization overview</p><h1 className="mt-1 font-display text-3xl font-bold uppercase">Site control</h1><p className="mt-2 text-sm text-muted-foreground">{new Intl.DateTimeFormat(undefined, { weekday: "long", month: "long", day: "numeric" }).format(now)}</p></div><Button variant="outline" size="icon" aria-label="Refresh overview" onClick={() => void load()} disabled={loading}><RefreshCw className={`size-4 ${loading ? "animate-spin" : ""}`} /></Button></header>
 {error ? <div role="alert" className="rounded-lg border border-destructive/30 bg-destructive/10 p-4"><p className="font-semibold">Overview unavailable</p><p className="mt-1 text-sm text-muted-foreground">{error}</p><Button variant="outline" className="mt-3" onClick={() => void load()}>Try again</Button></div> : null}
 <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[{ label: "Active shifts", value: active.length, icon: Clock3 }, { label: "Workers", value: workers.length, icon: Users }, { label: "Active sites", value: sites.filter((site) => site.status === "active").length, icon: MapPin }, { label: "Recorded hours", value: shifts.filter((shift) => shift.status !== "cancelled").reduce((sum, shift) => sum + hours(shift), 0).toFixed(1), icon: Activity }].map((item) => <StatCard key={item.label} label={item.label} value={loading || error ? "—" : String(item.value)} icon={item.icon} />)}</div>
 <div className="grid gap-8 lg:grid-cols-[1.5fr_1fr]"><section className="min-w-0"><div className="mb-4 flex items-center justify-between"><h2 className="font-display text-xl font-bold uppercase">Active shifts</h2><Button asChild variant="ghost" size="sm"><Link to="/admin/operations">Operations<ArrowUpRight className="size-4" /></Link></Button></div>{loading ? <div className="h-40 animate-pulse rounded-lg bg-muted" /> : active.length ? <ul className="divide-y divide-border">{active.map((shift) => <li key={shift.id} className="flex items-center justify-between gap-3 py-4"><div className="min-w-0"><p className="truncate font-semibold">{workers.find((worker) => worker.id === shift.worker_id)?.name ?? "Worker"}</p><p className="truncate text-xs text-muted-foreground">{sites.find((site) => site.id === shift.site_id)?.name ?? "Site"} · {shift.shift_type} shift</p></div><p className="shrink-0 font-display text-xl font-bold tabular-nums text-primary">{hours(shift).toFixed(1)} h</p></li>)}</ul> : <div className="border-y border-border py-12 text-center"><Clock3 className="mx-auto size-8 text-muted-foreground" /><p className="mt-3 font-semibold">No active shifts</p><p className="mt-1 text-sm text-muted-foreground">Staff check-ins will appear here.</p></div>}</section>
 <section><div className="mb-4 flex items-center justify-between"><h2 className="font-display text-xl font-bold uppercase">Recent activity</h2><Button asChild variant="ghost" size="sm"><Link to="/admin/activity">View all<ArrowUpRight className="size-4" /></Link></Button></div>{events.length ? <ul className="divide-y divide-border">{events.map((event) => <li key={event.id} className="py-3"><p className="text-sm font-semibold">{event.actor_name || "Organization"}</p><p className="text-sm text-muted-foreground">{event.action} · {event.entity}</p><p className="mt-1 text-xs text-muted-foreground">{new Date(event.created_at).toLocaleString()}</p></li>)}</ul> : <p className="border-y border-border py-12 text-center text-sm text-muted-foreground">No recorded activity yet.</p>}</section></div>
 <section><div className="mb-4 flex items-center justify-between"><h2 className="font-display text-xl font-bold uppercase">Site coverage</h2><Button asChild variant="ghost" size="sm"><Link to="/admin/sites">Sites<ArrowUpRight className="size-4" /></Link></Button></div>{sites.length ? <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{sites.map((site) => <div key={site.id} className="rounded-lg border border-border bg-card p-4"><div className="flex items-center justify-between gap-2"><p className="truncate font-semibold">{site.name}</p><MapPin className="size-4 shrink-0 text-primary" /></div><p className="mt-1 text-xs text-muted-foreground">{site.code} · {site.city}</p><p className="mt-4 text-sm"><strong>{active.filter((shift) => shift.site_id === site.id).length}</strong><span className="text-muted-foreground"> / {site.headcount_target} workers on shift</span></p></div>)}</div> : <p className="border-y border-border py-8 text-center text-sm text-muted-foreground">No sites registered.</p>}</section></div>;
}
