/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminInchargesRouteImport } from './routes/admin.incharges'
import { Route as AdminMachinesRouteImport } from './routes/admin.machines'
import { Route as AdminOperationsRouteImport } from './routes/admin.operations'
import { Route as AdminOperatorsRouteImport } from './routes/admin.operators'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSitesRouteImport } from './routes/admin.sites'
import { Route as AdminWorkersRouteImport } from './routes/admin.workers'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as StaffActiveRouteImport } from './routes/staff.active'
import { Route as StaffAttendanceRouteImport } from './routes/staff.attendance'
import { Route as StaffEndRouteImport } from './routes/staff.end'
import { Route as StaffHistoryRouteImport } from './routes/staff.history'
import { Route as StaffProfileRouteImport } from './routes/staff.profile'
import { Route as StaffStartRouteImport } from './routes/staff.start'
import { Route as StaffCompletedShiftIdRouteImport } from './routes/staff.completed.$shiftId'
import { Route as StaffHistoryShiftIdRouteImport } from './routes/staff.history.$shiftId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInchargesRoute = AdminInchargesRouteImport.update({
  id: '/incharges',
  path: '/incharges',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMachinesRoute = AdminMachinesRouteImport.update({
  id: '/machines',
  path: '/machines',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOperationsRoute = AdminOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOperatorsRoute = AdminOperatorsRouteImport.update({
  id: '/operators',
  path: '/operators',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSitesRoute = AdminSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWorkersRoute = AdminWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => AdminRoute,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffActiveRoute = StaffActiveRouteImport.update({
  id: '/active',
  path: '/active',
  getParentRoute: () => StaffRoute,
} as any)
const StaffAttendanceRoute = StaffAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => StaffRoute,
} as any)
const StaffEndRoute = StaffEndRouteImport.update({
  id: '/end',
  path: '/end',
  getParentRoute: () => StaffRoute,
} as any)
const StaffHistoryRoute = StaffHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => StaffRoute,
} as any)
const StaffProfileRoute = StaffProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StaffRoute,
} as any)
const StaffStartRoute = StaffStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => StaffRoute,
} as any)
const StaffCompletedShiftIdRoute = StaffCompletedShiftIdRouteImport.update({
  id: '/completed/$shiftId',
  path: '/completed/$shiftId',
  getParentRoute: () => StaffRoute,
} as any)
const StaffHistoryShiftIdRoute = StaffHistoryShiftIdRouteImport.update({
  id: '/$shiftId',
  path: '/$shiftId',
  getParentRoute: () => StaffHistoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/staff': typeof StaffRouteWithChildren
  '/admin/incharges': typeof AdminInchargesRoute
  '/admin/machines': typeof AdminMachinesRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/operators': typeof AdminOperatorsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sites': typeof AdminSitesRoute
  '/admin/workers': typeof AdminWorkersRoute
  '/staff/active': typeof StaffActiveRoute
  '/staff/attendance': typeof StaffAttendanceRoute
  '/staff/end': typeof StaffEndRoute
  '/staff/history': typeof StaffHistoryRouteWithChildren
  '/staff/profile': typeof StaffProfileRoute
  '/staff/start': typeof StaffStartRoute
  '/admin/': typeof AdminIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/staff/completed/$shiftId': typeof StaffCompletedShiftIdRoute
  '/staff/history/$shiftId': typeof StaffHistoryShiftIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/incharges': typeof AdminInchargesRoute
  '/admin/machines': typeof AdminMachinesRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/operators': typeof AdminOperatorsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sites': typeof AdminSitesRoute
  '/admin/workers': typeof AdminWorkersRoute
  '/staff/active': typeof StaffActiveRoute
  '/staff/attendance': typeof StaffAttendanceRoute
  '/staff/end': typeof StaffEndRoute
  '/staff/history': typeof StaffHistoryRouteWithChildren
  '/staff/profile': typeof StaffProfileRoute
  '/staff/start': typeof StaffStartRoute
  '/admin': typeof AdminIndexRoute
  '/staff': typeof StaffIndexRoute
  '/staff/completed/$shiftId': typeof StaffCompletedShiftIdRoute
  '/staff/history/$shiftId': typeof StaffHistoryShiftIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/staff': typeof StaffRouteWithChildren
  '/admin/incharges': typeof AdminInchargesRoute
  '/admin/machines': typeof AdminMachinesRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/operators': typeof AdminOperatorsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sites': typeof AdminSitesRoute
  '/admin/workers': typeof AdminWorkersRoute
  '/staff/active': typeof StaffActiveRoute
  '/staff/attendance': typeof StaffAttendanceRoute
  '/staff/end': typeof StaffEndRoute
  '/staff/history': typeof StaffHistoryRouteWithChildren
  '/staff/profile': typeof StaffProfileRoute
  '/staff/start': typeof StaffStartRoute
  '/admin/': typeof AdminIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/staff/completed/$shiftId': typeof StaffCompletedShiftIdRoute
  '/staff/history/$shiftId': typeof StaffHistoryShiftIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/register'
    | '/reset-password'
    | '/staff'
    | '/admin/incharges'
    | '/admin/machines'
    | '/admin/operations'
    | '/admin/operators'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/sites'
    | '/admin/workers'
    | '/staff/active'
    | '/staff/attendance'
    | '/staff/end'
    | '/staff/history'
    | '/staff/profile'
    | '/staff/start'
    | '/admin/'
    | '/staff/'
    | '/staff/completed/$shiftId'
    | '/staff/history/$shiftId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/register'
    | '/reset-password'
    | '/admin/incharges'
    | '/admin/machines'
    | '/admin/operations'
    | '/admin/operators'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/sites'
    | '/admin/workers'
    | '/staff/active'
    | '/staff/attendance'
    | '/staff/end'
    | '/staff/history'
    | '/staff/profile'
    | '/staff/start'
    | '/admin'
    | '/staff'
    | '/staff/completed/$shiftId'
    | '/staff/history/$shiftId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/register'
    | '/reset-password'
    | '/staff'
    | '/admin/incharges'
    | '/admin/machines'
    | '/admin/operations'
    | '/admin/operators'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/sites'
    | '/admin/workers'
    | '/staff/active'
    | '/staff/attendance'
    | '/staff/end'
    | '/staff/history'
    | '/staff/profile'
    | '/staff/start'
    | '/admin/'
    | '/staff/'
    | '/staff/completed/$shiftId'
    | '/staff/history/$shiftId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StaffRoute: typeof StaffRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/incharges': {
      id: '/admin/incharges'
      path: '/incharges'
      fullPath: '/admin/incharges'
      preLoaderRoute: typeof AdminInchargesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/machines': {
      id: '/admin/machines'
      path: '/machines'
      fullPath: '/admin/machines'
      preLoaderRoute: typeof AdminMachinesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/operations': {
      id: '/admin/operations'
      path: '/operations'
      fullPath: '/admin/operations'
      preLoaderRoute: typeof AdminOperationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/operators': {
      id: '/admin/operators'
      path: '/operators'
      fullPath: '/admin/operators'
      preLoaderRoute: typeof AdminOperatorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sites': {
      id: '/admin/sites'
      path: '/sites'
      fullPath: '/admin/sites'
      preLoaderRoute: typeof AdminSitesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/workers': {
      id: '/admin/workers'
      path: '/workers'
      fullPath: '/admin/workers'
      preLoaderRoute: typeof AdminWorkersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/active': {
      id: '/staff/active'
      path: '/active'
      fullPath: '/staff/active'
      preLoaderRoute: typeof StaffActiveRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/attendance': {
      id: '/staff/attendance'
      path: '/attendance'
      fullPath: '/staff/attendance'
      preLoaderRoute: typeof StaffAttendanceRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/end': {
      id: '/staff/end'
      path: '/end'
      fullPath: '/staff/end'
      preLoaderRoute: typeof StaffEndRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/history': {
      id: '/staff/history'
      path: '/history'
      fullPath: '/staff/history'
      preLoaderRoute: typeof StaffHistoryRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/profile': {
      id: '/staff/profile'
      path: '/profile'
      fullPath: '/staff/profile'
      preLoaderRoute: typeof StaffProfileRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/start': {
      id: '/staff/start'
      path: '/start'
      fullPath: '/staff/start'
      preLoaderRoute: typeof StaffStartRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/completed/$shiftId': {
      id: '/staff/completed/$shiftId'
      path: '/completed/$shiftId'
      fullPath: '/staff/completed/$shiftId'
      preLoaderRoute: typeof StaffCompletedShiftIdRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/history/$shiftId': {
      id: '/staff/history/$shiftId'
      path: '/$shiftId'
      fullPath: '/staff/history/$shiftId'
      preLoaderRoute: typeof StaffHistoryShiftIdRouteImport
      parentRoute: typeof StaffHistoryRoute
    }
  }
}

interface AdminRouteChildren {
  AdminInchargesRoute: typeof AdminInchargesRoute
  AdminMachinesRoute: typeof AdminMachinesRoute
  AdminOperationsRoute: typeof AdminOperationsRoute
  AdminOperatorsRoute: typeof AdminOperatorsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSitesRoute: typeof AdminSitesRoute
  AdminWorkersRoute: typeof AdminWorkersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminInchargesRoute: AdminInchargesRoute,
  AdminMachinesRoute: AdminMachinesRoute,
  AdminOperationsRoute: AdminOperationsRoute,
  AdminOperatorsRoute: AdminOperatorsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSitesRoute: AdminSitesRoute,
  AdminWorkersRoute: AdminWorkersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StaffHistoryRouteChildren {
  StaffHistoryShiftIdRoute: typeof StaffHistoryShiftIdRoute
}

const StaffHistoryRouteChildren: StaffHistoryRouteChildren = {
  StaffHistoryShiftIdRoute: StaffHistoryShiftIdRoute,
}

const StaffHistoryRouteWithChildren = StaffHistoryRoute._addFileChildren(
  StaffHistoryRouteChildren,
)

interface StaffRouteChildren {
  StaffActiveRoute: typeof StaffActiveRoute
  StaffAttendanceRoute: typeof StaffAttendanceRoute
  StaffEndRoute: typeof StaffEndRoute
  StaffHistoryRoute: typeof StaffHistoryRouteWithChildren
  StaffProfileRoute: typeof StaffProfileRoute
  StaffStartRoute: typeof StaffStartRoute
  StaffIndexRoute: typeof StaffIndexRoute
  StaffCompletedShiftIdRoute: typeof StaffCompletedShiftIdRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffActiveRoute: StaffActiveRoute,
  StaffAttendanceRoute: StaffAttendanceRoute,
  StaffEndRoute: StaffEndRoute,
  StaffHistoryRoute: StaffHistoryRouteWithChildren,
  StaffProfileRoute: StaffProfileRoute,
  StaffStartRoute: StaffStartRoute,
  StaffIndexRoute: StaffIndexRoute,
  StaffCompletedShiftIdRoute: StaffCompletedShiftIdRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StaffRoute: StaffRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
