/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as StaffProfileRouteImport } from './routes/staff.profile'
import { Route as StaffTimesheetRouteImport } from './routes/staff.timesheet'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffProfileRoute = StaffProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StaffRoute,
} as any)
const StaffTimesheetRoute = StaffTimesheetRouteImport.update({
  id: '/timesheet',
  path: '/timesheet',
  getParentRoute: () => StaffRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/staff': typeof StaffRouteWithChildren
  '/staff/profile': typeof StaffProfileRoute
  '/staff/timesheet': typeof StaffTimesheetRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/staff/profile': typeof StaffProfileRoute
  '/staff/timesheet': typeof StaffTimesheetRoute
  '/staff': typeof StaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/staff': typeof StaffRouteWithChildren
  '/staff/profile': typeof StaffProfileRoute
  '/staff/timesheet': typeof StaffTimesheetRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/staff' | '/staff/profile' | '/staff/timesheet' | '/staff/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/staff/profile' | '/staff/timesheet' | '/staff'
  id:
    | '__root__'
    | '/'
    | '/staff'
    | '/staff/profile'
    | '/staff/timesheet'
    | '/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StaffRoute: typeof StaffRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/profile': {
      id: '/staff/profile'
      path: '/profile'
      fullPath: '/staff/profile'
      preLoaderRoute: typeof StaffProfileRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/timesheet': {
      id: '/staff/timesheet'
      path: '/timesheet'
      fullPath: '/staff/timesheet'
      preLoaderRoute: typeof StaffTimesheetRouteImport
      parentRoute: typeof StaffRoute
    }
  }
}

interface StaffRouteChildren {
  StaffProfileRoute: typeof StaffProfileRoute
  StaffTimesheetRoute: typeof StaffTimesheetRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffProfileRoute: StaffProfileRoute,
  StaffTimesheetRoute: StaffTimesheetRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StaffRoute: StaffRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
