/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as StaffProfileRouteImport } from './routes/staff.profile'
import { Route as StaffStartRouteImport } from './routes/staff.start'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffProfileRoute = StaffProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StaffRoute,
} as any)
const StaffStartRoute = StaffStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => StaffRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/staff/profile': typeof StaffProfileRoute
  '/staff/start': typeof StaffStartRoute
  '/admin/': typeof AdminIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/staff/profile': typeof StaffProfileRoute
  '/staff/start': typeof StaffStartRoute
  '/admin': typeof AdminIndexRoute
  '/staff': typeof StaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/staff/profile': typeof StaffProfileRoute
  '/staff/start': typeof StaffStartRoute
  '/admin/': typeof AdminIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/staff'
    | '/staff/profile'
    | '/staff/start'
    | '/admin/'
    | '/staff/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/staff/profile' | '/staff/start' | '/admin' | '/staff'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/staff'
    | '/staff/profile'
    | '/staff/start'
    | '/admin/'
    | '/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  StaffRoute: typeof StaffRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/profile': {
      id: '/staff/profile'
      path: '/profile'
      fullPath: '/staff/profile'
      preLoaderRoute: typeof StaffProfileRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/start': {
      id: '/staff/start'
      path: '/start'
      fullPath: '/staff/start'
      preLoaderRoute: typeof StaffStartRouteImport
      parentRoute: typeof StaffRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StaffRouteChildren {
  StaffProfileRoute: typeof StaffProfileRoute
  StaffStartRoute: typeof StaffStartRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffProfileRoute: StaffProfileRoute,
  StaffStartRoute: StaffStartRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  StaffRoute: StaffRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
